src/prefab/component.rs, src/prefab/mod.rs
=> add_suport for all bevy primitive meshs

.github/workflows/ci.yaml, src/editor/core/persistance.rs, src/editor/core/task_storage.rs, src/editor/core/undo.rs, src/editor/ui/bot_menu.rs, src/editor/ui/change_chain.rs, src/editor/ui/inspector/components_order.rs, src/editor/ui/inspector/mod.rs, src/editor/ui/mod.rs, src/editor_registry/mod.rs
=> Issue 68/configurable components sorting

Cargo.toml, examples/platformer.rs, src/editor/ui/editor_tab.rs, src/editor/ui/hierarchy.rs, src/editor/ui/mod.rs, src/editor/ui/settings.rs, src/optional/mod.rs
Addresses https://github.com/rewin123/space_editor/issues/65
* No support for saving user preferences yet
=> Issue 65/new tabs behaviour

crates/editor_ui/src/camera_view.rs, crates/editor_ui/src/editor_tab.rs, crates/editor_ui/src/game_view.rs, crates/editor_ui/src/lib.rs, crates/editor_ui/src/settings.rs, crates/editor_ui/src/ui_registration.rs, crates/prefab/src/editor_registry/mod.rs, docs/shortcuts.md, modules/terrain_gen/src/lib.rs
=> Game camera view tab

assets/cube.scn.ron, assets/gate.scn.ron, assets/level.scn.ron, assets/monster.scn.ron, assets/parent_test.scn.ron, assets/test.scn.ron, assets/test_open_gltf.scn.ron
This updates the paths in the prefab files to match the renaming in commit 2e6731a6a2c7ae43e37620211a02f6920f8ea6a0.
=> Update ron paths

crates/editor_ui/Cargo.toml, crates/editor_ui/src/bottom_menu.rs, crates/editor_ui/src/lib.rs, crates/editor_ui/src/tools/gizmo.rs, crates/prefab/Cargo.toml, crates/prefab/src/component/path.rs, crates/shared/Cargo.toml
In an attempt to fix issue #140, I thought updating egui_dock might help because of issue Adanos020/egui_dock#183. Other dependencies then had to be updated due to conflicting versions of egui.
It did not fix issue #140, but hopefully this will prove useful anyway.
=> Update dependencies to use egui v0.24

crates/editor_core/src/gltf_unpack.rs
=> Fix children bug with gltf unpack #150 

crates/editor_ui/src/camera_view.rs, crates/editor_ui/src/editor_tab.rs, crates/editor_ui/src/lib.rs
=> Fix camera overlapping

README.md, docs/README.md, examples/event_example.rs
=> Add documentation regarding sending events

crates/editor_ui/Cargo.toml, crates/editor_ui/src/lib.rs
=> Fix grid with multiple cameras

crates/shared/Cargo.toml
Temporary fix before #157 as need wait to bevy_egui to update to new version
=> Set commit for egui_file crate before #157

crates/editor_ui/src/lib.rs, crates/undo/src/lib.rs
Small step for #134
Detached space_undo from EditorSet so that space_undo can be used separately
=> Detach undo

crates/editor_ui/src/camera_plugin.rs, crates/editor_ui/src/lib.rs, crates/editor_ui/src/selection.rs, crates/editor_ui/src/ui_plugin.rs, modules/bevy_xpbd_plugin/src/registry.rs
=> Clear mess in ui/lib.rs

crates/editor_ui/src/camera_view.rs, crates/editor_ui/src/lib.rs, crates/editor_ui/src/settings.rs, crates/editor_ui/src/ui_registration.rs, crates/prefab/src/plugins.rs, src/main.rs
- Switch between 2D and 3D game modes
- 2D game mode supports 2D cameras and necessary configurations
- 2D game mode supports simple sprites
=> Basic 2D Support

crates/editor_ui/src/hierarchy.rs
=> Fix selection

modules/bevy_mesh_terrain_plugin/src/terrain_chunks.rs
Fix crash bug by using try_insert
=> Bevy mesh terrain integration - Fix crash bug

.github/workflows/ci_develop.yaml, Cargo.toml, crates/editor_core/src/load.rs, crates/editor_core/src/toast.rs, crates/editor_ui/src/meshless_visualizer.rs, crates/editor_ui/src/mouse_check.rs, crates/prefab/Cargo.toml, crates/prefab/src/component/mod.rs, crates/prefab/src/component/player_start.rs, crates/prefab/src/save.rs, crates/prefab/src/spawn_system.rs, crates/shared/Cargo.toml, crates/shared/src/lib.rs, crates/shared/src/toast.rs
=> Toast support for prefab crate

crates/editor_ui/src/lib.rs, crates/editor_ui/src/menu_toolbars.rs
=> Change play button color

crates/editor_ui/src/inspector/mod.rs
Also move ``` fn inspector(...) ``` function to ui function of inspector tab. Also wrap show_component logic in fucntion for reusability
=> Add ability to show all components in entity and qol changes

crates/editor_ui/src/hierarchy.rs, crates/editor_ui/src/menu_toolbars.rs
- Allow to hide top and bottom menu with EditorUiShow state
- Remove duplication of adding Selected plugin
=> Fix separation

Cargo.toml, assets/scenes/cubes_camera_test.scn.ron, assets/scenes/level.scn.ron, assets/scenes/level_test.scn.ron, assets/scenes/load_test.scn.ron, assets/scenes/physics_object.scn.ron, crates/editor_core/src/load.rs, crates/editor_core/src/selected.rs, crates/editor_ui/Cargo.toml, crates/editor_ui/src/camera_plugin.rs, crates/editor_ui/src/camera_view.rs, crates/editor_ui/src/game_view.rs, crates/editor_ui/src/lib.rs, crates/editor_ui/src/meshless_visualizer.rs, crates/editor_ui/src/tools/gizmo.rs, crates/editor_ui/src/ui_registration.rs, crates/prefab/src/component/camera.rs, crates/prefab/src/component/mod.rs, crates/prefab/src/plugins.rs, crates/prefab/src/save.rs, modules/bevy_xpbd_plugin/src/registry.rs
Playmode: 
Camera view:
Resize camera view:
obs: There are a few cases where camera view still crashes, but this has reduced it significantly
=> first attemp on camera bug

Cargo.lock, Cargo.toml, README.md, assets/scenes/cube.scn.ron, crates/editor_ui/Cargo.toml, crates/editor_ui/src/camera_plugin.rs, crates/prefab/Cargo.toml, crates/prefab/src/plugins.rs, crates/prefab/src/save.rs, crates/prefab/src/spawn_system.rs, crates/prefab/src/sub_scene/mod.rs, game/Cargo.toml, game/src/lib.rs, game/src/main.rs, src/main.rs
Proposed solution wraps Game logic into a `game` folder, unloading the editor to be a source application and allowing more fined grain control over optimizations for game logic.
- Removed unnecessary editor feature
=> New way to deal with editor/game binaries

.github/workflows/ci.yaml, crates/editor_ui/src/colors.rs, crates/editor_ui/src/editor_style.rs, crates/editor_ui/src/game_view.rs, crates/editor_ui/src/hierarchy.rs, crates/editor_ui/src/menu_toolbars.rs, crates/editor_ui/src/settings.rs
- Adds buttons to warn that project was compiled in debug mode
- renames WARN_COLOR (previously was WARM)
- removes duplicated WARN_COLOR
- Can be removed in settings tab
=> warns-if-compiled-on-debug-build

.github/example-run/external_plugin.ron, .github/workflows/ci.yaml, .github/workflows/example_validation.yml, Cargo.lock, Cargo.toml, crates/prefab/src/spawn_system.rs, crates/prefab/src/sub_scene/mod.rs, external/editor_as_plugin/Cargo.toml, external/editor_as_plugin/src/main.rs
Addresses issue #208 
Example image result:
=> Issue 208 plugin as dependency

crates/editor_core/src/load.rs, crates/editor_ui/src/camera_view.rs, crates/editor_ui/src/change_chain.rs, crates/editor_ui/src/editor_style.rs, crates/editor_ui/src/inspector/components_order.rs, crates/editor_ui/src/inspector/events_dispatcher.rs, crates/editor_ui/src/inspector/mod.rs, crates/editor_ui/src/selection.rs, crates/editor_ui/src/settings.rs, crates/editor_ui/src/tool.rs, crates/editor_ui/src/tools/gizmo.rs, modules/bevy_xpbd_plugin/src/registry.rs
=> Issue 279 last pr

crates/prefab/src/component/player_start.rs, crates/prefab/src/editor_registry/mod.rs, crates/prefab/src/load.rs, crates/prefab/src/plugins.rs, crates/prefab/src/save.rs
Closes https://github.com/rewin123/space_editor/issues/224
=> Editor registry test

modules/bevy_xpbd_plugin/src/registry.rs
=> Fix instant rotation and shift for rigidbody 

Cargo.lock, Cargo.toml, crates/editor_core/src/gltf_unpack.rs, crates/editor_core/src/hotkeys.rs, crates/editor_core/src/selected.rs, crates/editor_core/src/task_storage.rs, crates/editor_core/src/toast.rs, crates/editor_tabs/src/lib.rs, crates/editor_tabs/src/schedule_editor_tab.rs, crates/editor_tabs/src/start_layout.rs, crates/editor_ui/src/camera_plugin.rs, crates/editor_ui/src/inspector/components_order.rs, crates/editor_ui/src/inspector/mod.rs, crates/editor_ui/src/lib.rs, crates/editor_ui/src/meshless_visualizer.rs, crates/editor_ui/src/selection.rs, crates/editor_ui/src/settings.rs, crates/editor_ui/src/tool.rs, crates/editor_ui/src/tools/gizmo.rs, crates/editor_ui/src/ui_registration.rs, crates/prefab/src/component/material.rs, crates/prefab/src/component/shape.rs, crates/prefab/src/component/sprite.rs, crates/prefab/src/load.rs, crates/prefab/src/spawn_system.rs, crates/prefab/src/sub_scene/mod.rs, crates/shared/src/toast.rs
This is my first ever pull request. I've probably made some errors, but most bugs relating to colors and the World have had an attempt at being fixed. Theres a few other bugs I don't know how to fix, mostly to do with rendering layers.
=> Mostly fixed world accesses and colors

crates/editor_ui/src/inspector/mod.rs
As a temporary fix I had turned off component reflection but I found one line to fix it. However I did change the show_component function to use PartialReflect so yall may want it different.
=> fixed reflect issues
