src/editor/ui/tools/gizmo.rs

This is from `clippy::unused_enumerate_index`, coming in Rust 1.75.

clippy: Remove unused enumerate index.

---

src/editor/ui/editor_tab.rs
src/editor/ui/inspector/mod.rs
src/editor/ui/inspector/resources.rs
src/editor/ui/mod.rs

Hey, was using the editor for something else today and realized I could not control/manage the bevy resources. This PR attempts to include a drop in simple resources tab using `bevy_inspector_egui::ui_for_resource`. Might be a good MVP for this tab.

Adds drop simple resources inspector

---

crates/editor/src/hierarchy.rs

This is a quick change that converts the `selectable_label`s being used for the hierarchy to `CollapsingHeader`s.
There is still an issue with some entities that are brought in from `.glb` files it seems and I would love some feedback about that.
Otherwise I believe that this is just a small feature update.

feat: Change the Hierarchy to support `egui::CollapsingHeader`

---

crates/editor_ui/src/camera_view.rs

If no camera is available, displays no camera message and add playmode camera button

Small camera view tab usability improvement

---

crates/editor_ui/src/bottom_menu.rs
crates/editor_ui/src/editor_tab.rs
crates/editor_ui/src/hierarchy.rs
crates/editor_ui/src/lib.rs
docs/README.md

And some style changes
Order of new tab popup window is preserved as defined in Enum (+ increased spacing between elements)
Mesh (and other bundles) have alphabetical order
* Renamed bot_menu to bottom_menu

Orders Button/Selectable lists by Name

---

crates/prefab/src/plugins.rs

Attempting to load a prefab with a `Camera3d` component fails due to `ScreenSpaceTransmissionQuality` not being registered. This fixes that.

Register ScreenSpaceTransmissionQuality

---

crates/editor_ui/src/lib.rs

Addresses the Issue discussed #64
Removes Debug Grid  and Camera Gizmos from CameraView

Removes gizmos from PlayCamera

---

Cargo.toml
crates/editor_ui/Cargo.toml
crates/editor_ui/src/editor_tab.rs
crates/editor_ui/src/inspector/assets.rs
crates/editor_ui/src/inspector/mod.rs
crates/editor_ui/src/inspector/runtime_assets.rs

Addresses issue https://github.com/rewin123/space_editor/issues/105 
Not a fully fledged asset inspector, but it should do the work for now

Simple assets inspector

---

crates/editor_ui/src/bottom_menu.rs
crates/shared/Cargo.toml

Addresses #148.
Currently relies on the git repo for [`egui_file`](https://github.com/Barugon/egui_file) until there is a new release that will have the required change on crates.io.

Fixed File browser for browsing `assets/`

---

crates/editor_ui/src/editor_tab.rs
crates/editor_ui/src/inspector/events.rs
crates/editor_ui/src/inspector/mod.rs
crates/prefab/src/editor_registry/mod.rs
crates/prefab/src/load.rs
examples/event_example.rs

This PR creates a new tab enabling the user to send events through the UI:
https://github.com/rewin123/space_editor/assets/3222456/aa1cfc51-cd13-4cd4-b931-55e1cdcefcf3
Events must be registered using `App.editor_registry_event()`, similar to `App.editor_registry()` for components. An example is provided in `/examples/event_example.rs`.
Currently events must implement Default, but a future goal is allowing the user to modify the event in the UI before sending it.

Support sending events through UI

---

Cargo.toml
README.md
crates/editor_ui/src/inspector/events_dispatcher.rs
crates/editor_ui/src/ui_registration.rs
crates/prefab/Cargo.toml
crates/prefab/src/editor_registry/mod.rs
docs/README.md
examples/custom_event.rs

This PR is supposed to be the continuation of [this commit 8d8d9ae72](https://github.com/rewin123/space_editor/commit/8d8d9ae72fa45e91b2209437f3dbbd4365c2d218).
Addresses https://github.com/rewin123/space_editor/issues/158 
```rs
// examples/custom_event
#[derive(Event, Default, Resource, Reflect, Clone)]
#[reflect(Resource)]
pub struct ToggleSpin {
speed: f32,
}
```
https://github.com/rewin123/space_editor/assets/14813660/b92433e7-c3a2-415a-92cf-ee74cc268f6e

Adds support for UI in custom events

---

crates/editor_ui/src/hierarchy.rs
crates/editor_ui/src/lib.rs

UX Pass `Show editor entities`

---

crates/undo/src/lib.rs
crates/undo/src/tests.rs

~85% code coverage for undo crate

Add undo tests

---

Cargo.toml
crates/editor_core/Cargo.toml
crates/editor_core/src/lib.rs
crates/editor_core/src/load.rs
crates/editor_core/src/toast.rs
crates/editor_ui/src/lib.rs
crates/editor_ui/src/menu_toolbars.rs
crates/editor_ui/src/meshless_visualizer.rs
crates/editor_ui/src/mouse_check.rs

Adds toasts of type:
- info
- warning
- success 
- error
Just need to add:
```rust
fn system_with_toast(
// ...
mut toasts: EventWriter<ToastMessage>,
) {
// ...
toasts.send_event(ToastMessage::new(
&format!("Despawning {entity:?}"),
egui_toast::ToastKind::Warning,
));
}
```

Adds toast support for user centered error handling

---

assets/scenes/cube.scn.ron
assets/scenes/cubes_camera_test.scn.ron
assets/scenes/level.scn.ron
assets/scenes/level_test.scn.ron
assets/scenes/load_test.scn.ron
assets/scenes/physics_loading_test.scn.ron
assets/scenes/physics_object.scn.ron
assets/scenes/test_open_gltf.scn.ron
crates/editor_core/src/toast.rs
crates/editor_ui/src/camera_plugin.rs
crates/editor_ui/src/camera_view.rs
crates/editor_ui/src/hierarchy.rs
crates/editor_ui/src/inspector/mod.rs
crates/editor_ui/src/lib.rs
crates/editor_ui/src/menu_toolbars.rs
crates/editor_ui/src/selection.rs
crates/editor_ui/src/settings.rs
crates/editor_ui/src/tools/gizmo.rs
crates/editor_ui/src/ui_registration.rs
crates/prefab/src/component/camera.rs
crates/prefab/src/component/shape.rs
crates/prefab/src/plugins.rs
crates/prefab/src/spawn_system.rs
crates/prefab/src/sub_scene/mod.rs
examples/loading_test.rs

- Button `|<<` had to be removed, the functionality is no longer available
- Clears Inspector and Hierarchy Filters
- Shapes are now spawnable and visible (Size was too small)
- Fixed some scenes, but scenes hierarchies seem to be incorrect due to new hashing loginc

Fix back in time button and adds 2d meshes

---

crates/editor_ui/src/hierarchy.rs
crates/editor_ui/src/inspector/mod.rs

- Add Component default size is calculated as early as possible to prevent long components changing its size
- Fix typo in clear filter (clear test => clear filter) 
- Only transform component is open by default
https://github.com/rewin123/space_editor/issues/255

`Add Component` button size

---

.github/workflows/ci.yaml
Cargo.toml
crates/editor_core/src/gltf_unpack.rs
crates/editor_core/src/hotkeys.rs
crates/editor_core/src/load.rs
crates/editor_tabs/src/lib.rs
crates/editor_tabs/src/start_layout.rs
crates/editor_ui/src/camera_view.rs
crates/editor_ui/src/game_view.rs
crates/editor_ui/src/hierarchy.rs
crates/editor_ui/src/inspector/mod.rs
crates/editor_ui/src/meshless_visualizer.rs
crates/editor_ui/src/settings.rs
crates/editor_ui/src/ui_registration.rs
crates/prefab/Cargo.toml
crates/prefab/src/editor_registry/mod.rs
crates/prefab/src/save.rs
crates/prefab/src/spawn_system.rs
crates/prefab/src/sub_scene/mod.rs

Partially Addresses https://github.com/rewin123/space_editor/issues/279

Issue 279 remove unnecessary unwraps

---

README.md

Just stumbled across this when trying to use `space_editor`

Fix `Usage - Editor` in README

---

Cargo.lock
Cargo.toml
crates/editor_ui/Cargo.toml
crates/editor_ui/src/asset_inspector/mod.rs
crates/editor_ui/src/camera_plugin.rs
crates/editor_ui/src/camera_view.rs
crates/editor_ui/src/change_chain.rs
crates/editor_ui/src/hierarchy.rs
crates/editor_ui/src/inspector/components_order.rs
crates/editor_ui/src/inspector/mod.rs
crates/editor_ui/src/lib.rs
crates/editor_ui/src/menu_toolbars.rs
crates/editor_ui/src/meshless_visualizer.rs
crates/editor_ui/src/mouse_check.rs
crates/editor_ui/src/selection.rs
crates/editor_ui/src/settings.rs
crates/editor_ui/src/sizing.rs
crates/editor_ui/src/tools/gizmo.rs
crates/editor_ui/src/ui_plugin.rs
crates/editor_ui/src/ui_registration.rs

Issue 227/UI test

---

crates/editor_core/src/gltf_unpack.rs
crates/editor_core/src/lib.rs
crates/editor_ui/src/game_view.rs
crates/editor_ui/src/lib.rs
crates/editor_ui/src/menu_toolbars.rs
crates/editor_ui/src/settings.rs

Fix camera vewport bug
